- compactify_spec_examples.py
- examples/spec-full.txt
- examples/spec-minimal.txt
- ocfl/object.py
- ocfl/version.py
- tests/test_object.py
- tests/test_version.py
> Update to remove old type=Object/Version, add object type URI

- ocfl/data/validation-errors.json
- ocfl/validator.py
- tests/test_validator.py
- tests/testdata/inventories/inv_1_good.json
Somewhat work in progress but perhaps a useful incremental step...
> Update fixtures, more validation

- .gitmodules
- ocfl-object.py
- ocfl/object.py
- tests/test_ocfl_object_script.py
> Check for --srcdir, fix messages

- ocfl/dispositor.py
- ocfl/identity.py
- ocfl/ntree.py
- ocfl/uuid_quadtree.py
- tests/test_dispositor.py
- tests/test_identity.py
Tidy and cover a couple more lines
> Tidy the Dispositors

- ocfl-object.py
- ocfl/object.py
- ocfl/validator.py
- tests/test_object.py
- tests/test_ocfl_object_script.py
> Initial implementation of update object

- setup.py
> Add package data to install

- CHANGES.md
- README
- ocfl-validate.py
- ocfl/object.py
- ocfl/object_utils.py
- tests/test_namaste.py
- tests/test_object.py
- tests/test_object_utils.py
> Add standalone inventory validation

- ocfl/data/validation-errors.json
> Fix paramater to error string E097

- ocfl/data/validation-errors.json
> Fix typo in E060 message

- ocfl/data/validation-errors.json
- ocfl/inventory_validator.py
- tests/test_validator.py
> Test for repeated logical paths

- ocfl/data/validation-errors.json
- ocfl/inventory_validator.py
- tests/test_validator.py
Add newly merged extra fixtures into tests, some comments with links to issues
> Extra fixtures

- ocfl/data/validation-errors.json
- ocfl/validator.py
- tests/test_validator.py
> Catch case of manifest not including a file in a previous version manifest

- ocfl/data/validation-errors.json
- ocfl/inventory_validator.py
- ocfl/validator.py
- tests/test_inventory_validator.py
- tests/test_validator.py
> Catch inconsistent id between versions

- tests/test_validator.py
> Enable test E010_missing_versions

- ocfl/data/validation-errors.json
- ocfl/inventory_validator.py
- tests/test_inventory_validator.py
- tests/test_validator.py
> Check digest match between states for same digest algorithm

- CHANGES.md
- ocfl/data/validation-errors.json
- ocfl/validator.py
- tests/test_validator.py
> Does extra directory look like version dir?

- ocfl/store.py
> Fix key to extension per 1.0 spec

- .github/workflows/action.yml
- CHANGES.md
- ocfl/data/validation-errors.json
- ocfl/validator.py
- tests/test_validator.py
> Add test for E103, bad spec version sequence

- .github/workflows/action.yml
- CHANGES.md
- docs/demo_ocfl_object_script.md
- docs/demo_ocfl_root_script.md
- docs/demo_ocfl_sidecar_script.md
- docs/demo_ocfl_validate_script.md
- docs/demo_using_bagit_bags.md
- ocfl/_version.py
- setup.py
> Prep for 2.0 release on pypi

- docs/demo_ocfl_object_script.md
- docs/demo_ocfl_root_script.md
- docs/demo_ocfl_sidecar_script.md
- docs/demo_ocfl_validate_script.md
- docs/demo_using_bagit_bags.md
- ocfl-object.py
- ocfl/bagger.py
- tests/test_bagger.py
- tests/test_demo_using_bagit_bags.py
> Allow Bagging-Date to be set, set in demo

- README
- docs/api.rst
- docs/command_line.rst
- docs/conformance.rst
- docs/index.rst
- docs/installation.rst
> Add installation section to docs
